Area.create!(name: "DOM A")
Area.create!(name: "DOM B")
Area.create!(name: "DOM C")
Area.create!(name: "DOM D")
Area.create!(name: "DOM F")
User.create!(name: "admin", email: "admin@gmail.com", room: "F507", position: 0, area_id: 5, password: "345345", confirmed_at: Time.zone.now)
User.create!(name: "Tay-User", email: "user@gmail.com", room: "F506", position: 2, area_id: 4, password: "345345", confirmed_at: Time.zone.now)
User.create!(name: "Tay-User-2", email: "user2@gmail.com", room: "F504", position: 2, area_id: 2, password: "345345", confirmed_at: Time.zone.now)
User.create!(name: "Tay-Seller", email: "seller@gmail.com", room: "F505", position: 1, area_id: 3, password: "345345", confirmed_at: Time.zone.now)
Category.create!(name: "Cơm", description: "Mô tả về cơm")
Category.create!(name: "Bún - Phở", description: "Mô tả về Bún - Phở")
Category.create!(name: "Bánh mỳ", description: "Mô tả về Bánh mỳ")
Category.create!(name: "Trà sữa", description: "Mô tả về Trà sữa")
