Area.create!(name: "DOM A")
Area.create!(name: "DOM B")
Area.create!(name: "DOM C")
Area.create!(name: "DOM D")
Area.create!(name: "DOM F")
User.create!(name: "admin", email: "admin@gmail.com", room: "f507", position: 0, area_id: 5, password: "345345", confirmed_at: Time.zone.now)
User.create!(name: "user", email: "user@gmail.com", room: "f506", position: 2, area_id: 4, password: "345345", confirmed_at: Time.zone.now)
User.create!(name: "seller", email: "seller@gmail.com", room: "f505", position: 1, area_id: 3, password: "345345", confirmed_at: Time.zone.now)
